
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"  # Expose the hub on port 4444
    networks:
      - grid  
    environment:
      - GRID_TIMEOUT=30000
      - GRID_BROWSER_TIMEOUT=30000

  node-chrome:
    image: selenium/node-chrome:latest
    container_name: chrome
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub  # Hub service name
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - grid  
    depends_on:
      - selenium-hub
    ports:
      - "5555:5555"  # Expose node port for debugging purposes
    volumes:
      - /dev/shm:/dev/shm  # To avoid memory issues

  node-firefox:
    image: selenium/node-firefox:latest
    container_name: firefox
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub  # Hub service name
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
     - grid
    depends_on:
      - selenium-hub
    ports:
      - "5556:5556"
    volumes:
      - /dev/shm:/dev/shm	
networks:
 grid:
  driver: bridge